### ISSUE TITLE
Исправить адаптив подвала сайта

### ISSUE THREAD

**Issue by Ge5akl** [ISRPO2019/ISRPO2019.github.io#168]
Текущая версия:
![image](https://user-images.githubusercontent.com/38038269/80703148-4c4ca980-8af3-11ea-9c62-fbbc1248b378.png)
Макет: 
![image](https://user-images.githubusercontent.com/38038269/80703201-68e8e180-8af3-11ea-9bde-afa7ad8aa41b.png)

**Comment by MamaikAn** [comment]
Сейчас на разрешениях 992-1199 отображается планшетная версия. Необходимо, чтобы отображалась пк версия для 1199+
