### ISSUE TITLE
Исправить страницу отдельного товара

### ISSUE THREAD

**Issue by FluffyF1sh** [ISRPO2019/ISRPO2019.github.io#169]
Исправить отображение картинки товара в соответствии с макетом:
![image](https://user-images.githubusercontent.com/37347360/80703986-d5b0ab80-8af4-11ea-85fb-45c28b6e3414.png)
Текущая версия:
![image](https://user-images.githubusercontent.com/37347360/80704025-e7924e80-8af4-11ea-9079-9fe6ea2c82b6.png)
Необходимо добавить отступы отталкиваясь от данных в макете.

**Comment by MamaikAn** [comment]
Сейчас отступы 15. Еще кнопку поправить 
![image](https://user-images.githubusercontent.com/38722519/80704171-caf21880-8aec-11ea-9810-aa5093bca32c.png)
