### ISSUE TITLE
Создать локальное хранилище для товаров

### ISSUE THREAD

**Issue by MamaikAn** [ISRPO2019/ISRPO2019.github.io#29]
Необходимо создать локальное хранилище для товаров (local storage - js). 
Заполнение базы данных сейчас стоит задача у дизайнеров. 
Необходимые поля: 
- id (число);
- описание товара (строка);
- тип (три состояния - мужской/женский/детский);
- цена (число с плавающей точкой);
- бренд (строка - название);
- страна (строка - название);
- механизм (два состояния - аналоговые/цифровые);
- цвет (строка - название);
- массив комментариев:
  - имя автора (строка);
  - текст комментария (строка);
  - дата (date как на макете);
  - номер телефона (просто будем его хранить).;
- массив обзоров:
  - имя автора (строка);
  - оценка (число);
  - текст комментария (строка);
  - дата (date как на макете);
  - номер телефона (просто будем его хранить).

**Comment by AlekseyVasilyev** [comment]
Пол женский, механизм автоматический подзавод, цвет белый, страна Швейцария, цена 30.000
![ZtXNy7zfwHE](https://user-images.githubusercontent.com/38579888/69794834-68ff5100-11e4-11ea-9e78-34dded479a3e.jpg)

**Comment by AlekseyVasilyev** [comment]
Пол мужской, механизм ручной подзавод, цвет синий, страна Китай, цена 20.000
![-wt_Eu1_nWQ](https://user-images.githubusercontent.com/38579888/69795045-db703100-11e4-11ea-819b-f2ff8a983e5c.jpg)

**Comment by AlekseyVasilyev** [comment]
Пол детский, механизм кварцевый, цвет розовый, страна Япония, цена 3000
![5rPhuWQUYUY](https://user-images.githubusercontent.com/38579888/69795090-f478e200-11e4-11ea-81f6-b4ea45ae7957.jpg)

**Comment by AlekseyVasilyev** [comment]
пол мужской, механизм аналоговый, цвет синий, страна Германия, цена 43.000
![carl-von-zeyten-herren-uhr-cvz0042rbl-baden-baden-automatik](https://user-images.githubusercontent.com/38579888/69795219-2f7b1580-11e5-11ea-9141-7f2ded566559.jpg)

**Comment by MamaikAn** [comment]
Добавить к локальному хранилищу поле id.
Отобразить содержимое хранилища на странице каталога
**UPD:** обновил первый коммент

**Comment by MamaikAn** [comment]
Дополнить хранилище набором комментариев и отзывов, описанием товара. Можно использовать Lorem Ipsum.

**Comment by TeplCold** [comment]
Fixes #29, #63 or #81
