### ISSUE TITLE
Сделать дизайн и вёрстку идентичными

### ISSUE THREAD

**Issue by FluffyF1sh** [ISRPO2019/ISRPO2019.github.io#31]
В ходе тестирования выявилось, что текущая вёрстка и ранее представленный макет не соответствуют друг другу.

**Comment by TeplCold** [comment]
Duplicate of #67
Duplicate of #68 
Duplicate of #69
Duplicate of #74

**Comment by MamaikAn** [comment]
> В ходе тестирования выявилось, что текущая вёрстка и ранее представленный макет не соответствуют друг другу.

Нужен список проблемных мест
