### ISSUE TITLE
Доработка тестовых сценариев фильтрации

### ISSUE THREAD

**Issue by FluffyF1sh** [ISRPO2019/ISRPO2019.github.io#40]
В связи с правками в тз нужно доработать существующие сценарии тестирования блока фильтрации.

**Comment by Ge5akl** [comment]
https://docs.google.com/document/d/1DAp4bVL_nwPq5Eps5uYffWU4Js1ikTPaInspINccUXs/edit?disco=AAAADyRzerQ
