### ISSUE TITLE
Исправить блок товаров и сделать адаптив

### ISSUE THREAD

**Issue by FluffyF1sh** [ISRPO2019/ISRPO2019.github.io#90]
Изменить блок товаров в соответствии с макетом.

**Comment by TeplCold** [comment]
Переназначил в связи с болезнью.

**Comment by MamaikAn** [comment]
Требуется исправить участки кода [#152 ](https://github.com/ISRPO2019/ISRPO2019.github.io/pull/152), оставил комментарии в pull request
